# Generated by Django 5.1.2 on 2024-11-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genero_cidade_autor_editora_livro_user_emprestimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='autor',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='autor',
            name='data_nasc',
            field=models.DateField(default='1600-12-01'),
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='autor',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='editora',
            name='cnpj',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='editora',
            name='data_fund',
            field=models.DateField(default='1600-12-01'),
        ),
        migrations.AddField(
            model_name='editora',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='editora',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_nasc',
            field=models.DateField(default='1600-12-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
